### ISSUE TITLE
我也在学习这个,我使用unidbg加载不了so是为什么 大神可以讲解一下嘛?

### ISSUE THREAD

**Issue by fwktzs333** [Ccccccccvvm/DouYin_algorithm#1]
我也在学习这个,我使用unidbg加载不了so是为什么 大神可以讲解一下嘛?

**Comment by Ccccccccvvm** [comment]
贴一下代码，或者错误代码。

**Comment by fwktzs333** [comment]
package com.dy.sixgod;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.Module;
import com.github.unidbg.arm.backend.Unicorn2Factory;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.file.linux.AndroidFileIO;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.linux.file.SimpleFileIO;
import com.github.unidbg.memory.Memory;

import java.io.File;
import java.io.IOException;

public class JniDispatch128 extends AbstractJni implements IOResolver<AndroidFileIO> {
    private final AndroidEmulator emulator;
    private final Memory memory;
    private final Module module;

    private final VM vm;
    JniDispatch128() throws IOException {
        emulator = AndroidEmulatorBuilder
                .for64Bit()
                .setProcessName("com.ss.android.ugc.aweme")
                .addBackendFactory(new Unicorn2Factory(true))
                .build();


        emulator.getBackend().registerEmuCountHook(10000);
        emulator.getSyscallHandler().addIOResolver(this);
        emulator.getSyscallHandler().setVerbose(true);
        emulator.getSyscallHandler().setEnableThreadDispatcher(true);

        memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        vm = emulator.createDalvikVM(new File("unidbg-android/src/test/java/com/dy/sixgod/dy2590.apk"));
        vm.setVerbose(false);
        vm.setJni(this);

        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/java/com/dy/sixgod/metasec.so"), true);
        module = dm.getModule();

        DvmClass a = vm.resolveClass("ms/bd/c/k");
        DvmClass b = vm.resolveClass("ms/bd/c/a0", a);
        vm.resolveClass("com/bytedance/mobsec/metasec/ml/MS", b);

        dm.callJNI_OnLoad(emulator);


    }

    @Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        if (pathname.equals("/proc/self/exe")){
            System.out.println("EXE");
            return FileResult.<AndroidFileIO>success(new SimpleFileIO(oflags, new File("C:\\Users\\Administrator\\Desktop\\unidbg-master\\unidbg-android\\src\\test\\java\\com\\dy\\sixgod\\dy2590.apk"), pathname));
        }
        return null;
    }

    @Override
    public int getStaticIntField(BaseVM vm, DvmClass dvmClass, String signature) {
        if ("com/bytedance/mobsec/metasec/ml/MS->a()V".equals(signature)) {
            return 0x40;
        }
        throw new UnsupportedOperationException(signature);
    }
    @Override
    public void callVoidMethod(BaseVM vm, DvmObject<?> dvmObject, String signature, VarArg varArg) {
        switch (signature) {
            case "com/bytedance/mobsec/metasec/ml/MS->a()V":
                System.out.println("> Patched: com/bytedance/mobsec/metasec/ml/MS->a()V");
                return;
        }
        super.callVoidMethod(vm, dvmObject, signature, varArg);
    }
    public static void main(String[] args) throws Exception{
        JniDispatch128 text = new JniDispatch128();
    }
}




[18:47:51 517]  WARN [com.github.unidbg.arm.AbstractARM64Emulator] (AbstractARM64Emulator$1:66) - Read memory failed: address=0x77df9505, size=8, value=0x0
[18:47:51 518]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x410d8de4[libmetasec_ml.so]0xd8de4 exception sp=unidbg@0xbffff4b0, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=2ms
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:210)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.dy.sixgod.JniDispatch128.<init>(JniDispatch128.java:52)
	at com.dy.sixgod.JniDispatch128.main(JniDispatch128.java:83)

**Comment by Ccccccccvvm** [comment]
at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:210)   
BaseVM.java:210 这行注释掉。

**Comment by fwktzs333** [comment]
我可以通过tg 或者什么联系到你嘛?
